ls:
  .js: kebab-case
  .ts: kebab-case
  .tsx: kebab-case
  .json: kebab-case
  .d.ts: kebab-case
  src/**:
    .dir: kebab-case
  public/**:
    .dir: kebab-case

ignore:
  - .git
  - node_modules
  - vite.config.ts
  - .commitlintrc.json
  - tsconfig.node.json
